# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: La Web del Videojuego
description: >-
  Artículos de opinión y análisis de videojuegos.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lawebdelvideojuego.com"
title_image: /assets/images/logo1.png
twitter_username: jbilbob
github_username: jbilbo
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
